# Generated by Django 5.1.5 on 2025-02-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
